[package]
name = "codecrafters-grep"
version = "0.1.0"
authors = ["JP Verkamp <me@jverkamp.com>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
thiserror = "1.0.63"
